# -*- coding: utf-8 -*-
"""Tensorflow_study5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S44FCx4BAh4kN2hh3SHnGJz4QkCVkTEo
"""

# 回归分析
import tensorflow as tf
from tensorflow import keras
(x_train,y_train),(x_test,y_test) = keras.datasets.boston_housing.load_data()
# 打印相对应的结果
# print(x_train.shape," ",y_train.shape) 
# print(x_test.shape," ",y_test.shape)
# 以boston_housing数据集为基础构建模型
model = keras.Sequential([
    keras.layers.Dense(32,activation='sigmoid',input_shape=(13,)),
    keras.layers.Dense(32,activation='sigmoid'),
    keras.layers.Dense(32,activation="sigmoid"),
    keras.layers.Dense(1)
])
# 使用密集连接层构建模型
model.compile(optimizer=keras.optimizers.SGD(0.1),loss='mean_squared_error',metrics=['mse'])
# 编译模型
model.summary()
# 迭代训练模型
model.fit(x_train,y_train,batch_size=50,epochs=50,validation_split=0.1,verbose=1)
# 定义返回结果
result = model.evaluate(x_test,y_test)
print(model.metrics_names)
print(result)